### ISSUE TITLE
can you provide the trained model? thanks~

### ISSUE THREAD

**Issue by visonpon** [pzins/Data-Driven-3D-Reconstruction-of-Dressed-Humans-from-Sparse-Views#1]

**Comment by pzins** [comment]
Hello,

Unfortunately, we use the commercial dataset Renderpeople to train our model so we are not authorized to release a pretrained model. If you have access to Renderpeople meshes, you can easily generate the images, silhouettes and calibrations and re-train our network.

**Comment by visonpon** [comment]
what a pity, but also thanks for sharing this wonderful work~
