### ISSUE TITLE
Using THuman2.0 dataset 

### ISSUE THREAD

**Issue by sinamoghimi73** [pzins/Data-Driven-3D-Reconstruction-of-Dressed-Humans-from-Sparse-Views#2]
Hello,

Thanks for your great work! I have a question! In your source code you have used the `renderpeople` dataset which if Im not mistaken, is for a commercial usage. I was wondering if this source code also works for `THuman2.0` dataset? If not, is there any future plans to provide this support?

I have done some modification to make it work for `THuman2.0` but my loss values in orthogonal projection, fluctuates between 1 and 10 and it seems the network cannot train. I would be grateful if you could guide me.

Sincerely

**Comment by pzins** [comment]
Hello,

Yes, it should be possible to use data from `THuman2.0`, I have already tested it. 
You need to be careful with the scale because `Renderpeople` meshes are in cm whereas `Thuman2.0` are in m I think. You probably need to adjust the sampling parameters **sigma**, **B_MIN** and **B_MAX**  in `./data/TrainDataset.py`

**Comment by sinamoghimi73** [comment]
Thank you for your kind response. I have a couple of questions.

1- May I know what values did you choose for the `sigma`, `B_MIN` and `B_MAX`.
2- Should I modify anything in the rendering script?

Sincerely

**Comment by pzins** [comment]
With `Renderpeople` data I used:
- sigma = 5
- B_MIN =  [-128, -28, -128]
- B_MAX = [128, 228, 128]

If you want to use `THuman2.0` data I think the easiest thing to do is just to scale by 100 the meshes such that they are in cm as in `Renderpeople`. Then, everything should work with this code and these parameters.

If I remember correctly, in `THuman2.0`, the meshes are aligned in translation but with different rotations. If you want that all the meshes look in the same direction you can probably use the `global_orient` parameter from the `smplx` fittings provided in **https://github.com/ytrock/THuman2.0-Dataset**. This step might be useful but is not necessary to train the model.

**Comment by sinamoghimi73** [comment]
Many thanks for your time and guidance.

I Implement these suggestions to see the result. Is it possible to write here for further questions?

Sincerely

**Comment by pzins** [comment]
You're welcome.
Sure, you can write here for further questions.

**Comment by sinamoghimi73** [comment]
Hello,

I have finally got to a result. The output is somehow flipped. I was wondering if you could guide me to fix this flipped output?

Sincerely 

![image](https://user-images.githubusercontent.com/45493197/227195326-6455f4ce-488d-40b8-9e57-0b6a869d2929.jpeg)

**Comment by pzins** [comment]
Hello,

You can probably just flip the vertices around the Y axis in ```utils/evaluator.py``` (line 161):
```
verts[:,1] *= -1
```

**Comment by sinamoghimi73** [comment]
Thank you very much for your kind guidance.

Sincerely
