### ISSUE TITLE
Problem in render_data_scene.py

### ISSUE THREAD

**Issue by miladranaeisiadat** [pzins/Data-Driven-3D-Reconstruction-of-Dressed-Humans-from-Sparse-Views#3]
Hello pzins, 

Thanks for your excellent work and open sourcing your code. I have successfully rendered and reconstructed your code on THuman2.0 in perspective and orthographic projection (case 1) but when trying to render THuman2.0 objects in case 2 (render_data_scene) then I'll get the black JPG images as a result (can see in the attached image). May I ask you to tell me where I must change in the "render_data_scene.py" to get an appropriate result? 

![23_30_00](https://user-images.githubusercontent.com/41792322/231180866-cf4472a4-f7e7-46b3-823d-c279973825b4.jpg)

Big thanks for your amazing work!

**Comment by pzins** [comment]
Hello,

Sorry for the late answer.
If the rendered image is black it probably means that the camera is not looking toward the mesh.
You can change the camera parameters (lines 155 to 165) or the position of the mesh (lines 222 to 227).

Also remember that this script assumes the meshes to be specified in centimeters.

I Hope this can help you.

**Comment by miladranaeisiadat** [comment]
I really appreciate pzins for your response. As you said I already solved the issue with changing the camera parameters and scaling vertices. Again big thanks for response and consideration.
