### ISSUE TITLE
How can convert real-world camera parameters to params.npy for real-world data?

### ISSUE THREAD

**Issue by miladranaeisiadat** [pzins/Data-Driven-3D-Reconstruction-of-Dressed-Humans-from-Sparse-Views#4]
Hello dear pzins,

I tried to train and inference your wonderful code in the case 2 when the subject is randomly positioned in the scene and multiple perspective cameras observe the scene. I rendered the THuman2.0 dataset and trained on it as well as inference after few modifications. 
Now going to apply the inference the trained model on the real world data which taken from 5 cameras in the different angles. Really appreciate you if guide me how can I calculate the camera parameters? Every camera has intrinsic and extrinsic parameter and how can I use this params and converting to your .npy params which including R, scale and so one? you already helped me to solve many issue and appreciate you if helping me to solve this problem with camera parameters as well.

**Comment by pzins** [comment]
Hello,

You probably need to modify the script process_inference_data_scene.py as it works with synthetic data rendered with OpenGL.
If you have real data, your projection matrix will be K @ Rt, and you don't need the clipping part or deleting a row from OpenGL.
